[package]
name = "pperf"
version = "0.1.0"
authors = ["Johannes Lundberg <johalun0@gmail.com>"]

[dependencies]
clap = "2.32.0"
num_cpus = "1.8.0"
log = "0.4"
env_logger = "0.5.13"
daemonize = "0.3.0"
net2 = "0.2.33"
libc = "0.2.43"
chan-signal = "0.3.2"
time = "0.1.40"
