[package]
name = "pperf"
version = "0.1.1"
authors = ["Johannes Lundberg <johalun0@gmail.com>"]

[dependencies]
clap = "^2.33.3"
num_cpus = "^1.8"
log = "^0.4"
env_logger = "^0.9"
daemonize = "^0.3"
net2 = "^0.2.33"
libc = "^0.2.43"
signal-hook = "^0.3.9"
time = "^0.1.40"
